# Generated by Django 3.0.4 on 2020-03-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyClass',
            fields=[
                ('Job_Profile_ID', models.CharField(max_length=100)),
                ('JobProfile', models.CharField(max_length=100)),
                ('Salary', models.IntegerField()),
                ('Employee_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeClass',
            fields=[
                ('Employee_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Phone', models.IntegerField()),
                ('City', models.CharField(max_length=100)),
            ],
        ),
    ]
